name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_URL: http://${{ secrets.FTP_SERVER }}/api
      - run: npm ci
      - run: npm run build --if-present
      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          args: --profile --ignore-platform-reqs
          working_dir: "server/"
      - name: "Add server file"
        run: |
          mkdir ./dist/api
          cp -r ./server/* ./dist/api
      - name: Deploy
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./dist/"
          remote_dir: "./${{ secrets.FTP_SERVER }}/"
          delete: "false"
